### PR TITLE
backLinks strip /edit from url

### PR DESCRIPTION
**Pull request by joefitter**
- added `getBackLink` method to base controller - this is called by the locals method and alters the value of `res.locals.backLink`
- if `backLink` is empty string, do nothing
- if `req.params.action === edit`, append `/edit`
- if no `baseUrl`, prepend `/`

### CODE REVIEW

**Comment by joefitter** [comment]
@easternbloc @JoeChapman @daniel-ac-martin mind having a 🔭

**Comment by JoeChapman** [comment]
I like this because it wraps the code required to return the back link, into a method, which is how we are doing it for getting the next step et al. LGTM, @easternbloc?

**Comment by joefitter** [comment]
@gxxm @bendiggle @daniel-ac-martin @easternbloc can I get a another 👍  please?

**Comment by joefitter** [comment]
Closing as will be included when so-master merged

**Pull request closed without merging**
