### PR TITLE
date-controller broken when saving values

### PR DESCRIPTION
**Pull request by joefitter**
- passed all args to super.saveValues - was missing res and callback

### CODE REVIEW

**Comment by joefitter** [comment]
@JoeChapman @easternbloc @daniel-ac-martin @gxxm quick bugfix

**Comment by joefitter** [comment]
https://github.com/UKHomeOffice/hof-controllers/issues/54

**Comment by easternbloc** [comment]
LGTM.

**Comment by easternbloc** [comment]
@JoeChapman @daniel-ac-martin can you give this a 👍 and we can get it merged.

**Comment by JoeChapman** [comment]
LGTM

**Comment by easternbloc** [comment]
done and done

**Comment by joefitter** [comment]
⚡

**Pull request merged**
