### PR TITLE
bugfix - null and undefined backlinks were being cast as string with …

### PR DESCRIPTION
**Pull request by joefitter**
…/ prepended

### CODE REVIEW

**Comment by joefitter** [comment]
@JoeChapman @easternbloc @daniel-ac-martin @danielepolencic mind having a quick look at this? `backLink: null|undefined` was being ignored

**Comment by danielepolencic** [comment]
LGTM 👍

**Comment by joefitter** [comment]
@easternbloc @JoeChapman @daniel-ac-martin can I get another 👍  please?

**Comment by joefitter** [comment]
@easternbloc @JoeChapman @daniel-ac-martin bump ;)

**Comment by JoeChapman** [comment]
LGTM

**Pull request merged**
